spring:
  data:
    mongodb:
      uri: mongodb://vibe:vibe_local_2026@localhost:27017/vibe_rooms?authSource=admin
    redis:
      host: localhost
      password: vibe_redis
  kafka:
    listener:
      auto-startup: false

logging:
  level:
    com.vibe: DEBUG
