package com.vibe.common.enums;
public enum NotificationType {
    NEW_MESSAGE, POST_LIKE, POST_COMMENT, NEW_FOLLOWER,
    ROOM_INVITE, STREAK_ACHIEVED, TOKEN_EARNED, STATUS_LIKE,
    STATUS_COMMENT, FRIEND_REQUEST, CASHOUT_PROCESSED, SYSTEM, SYSTEM_ANNOUNCEMENT
}
